// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace CwNetTest.TestCases.Ukraine.National_MT_Outgoing
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("SpecFlowFeature", Description="\tIn order to National MT Outgoing\r\n\tAs a bank user\r\n\tI want to make a transfer", SourceFile="TestCases\\Ukraine\\National_MT_Outgoing\\National_MT_Outgoing.feature", SourceLine=0)]
    public partial class SpecFlowFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "National_MT_Outgoing.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "SpecFlowFeature", "\tIn order to National MT Outgoing\r\n\tAs a bank user\r\n\tI want to make a transfer", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables(string firstTabPage, string debitAccount, string actualDate, string bankCode, string creditAccount, string reason, string secondTabPage, string currentBpId, string prepareBP, string approveBP, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "National_Outgounting_Transfer"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Run Natioanl_outgounting_Transfer with example tables", @__tags);
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
testRunner.Given(string.Format("Bank User have been on {0} tab page", firstTabPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
testRunner.When(string.Format("Bank User enter debit account {0} for National_MT_Outgoing tab page", debitAccount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 10
testRunner.And(string.Format("Bank User enter actual date {0} for National_MT_Outgoing tab page", actualDate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
testRunner.And("Bank User enter random amount for transfer for National_MT_Outgoing tab page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 12
testRunner.And("Bank User enter random doc number for National_MT_Outgoing tab page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 13
testRunner.And(string.Format("Bank User enter credit bank code {0} for National_MT_Outgoing tab page", bankCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 14
testRunner.And(string.Format("Bank User enter credit account {0} for National_MT_Outgoing tab page", creditAccount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 15
testRunner.And(string.Format("Bank User enter reason {0} for National_MT_Outgoing tab page", reason), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 16
testRunner.And(string.Format("Bank User finish prepare BP for {0} transfer", prepareBP), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
testRunner.Then(string.Format("Bank User have been on {0} tab page", secondTabPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 18
testRunner.And(string.Format("Bank User enter current BpId {0}", currentBpId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
testRunner.And(string.Format("Bank User approve BP for {0} transfer", approveBP), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 20
testRunner.And("Bank User check result for National_MT_Outgoing transfer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, CARD_NMT_OUT", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_CARD_NMT_OUT()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("CARD_NMT_OUT", "260500194184.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "CARD_NMT_OUT", "CARD_NMT_OUT", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, CARD_NMT_OUT_EBANK_PI", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_CARD_NMT_OUT_EBANK_PI()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("CARD_NMT_OUT_EBANK_PI", "26050210022978.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "CARD_NMT_OUT_EBANK_PI", "CARD_NMT_OUT_EBANK_PI", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, CARD_NMT_OUT_EBANK_PI_SO", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_CARD_NMT_OUT_EBANK_PI_SO()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("CARD_NMT_OUT_EBANK_PI_SO", "260500194184.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "CARD_NMT_OUT_EBANK_PI_SO", "CARD_NMT_OUT_EBANK_PI_SO", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, CARD_NMT_OUT_IBANK", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_CARD_NMT_OUT_IBANK()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("CARD_NMT_OUT_IBANK", "260500194184.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "CARD_NMT_OUT_IBANK", "CARD_NMT_OUT_IBANK", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, CARD_NMT_OUT_PF", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_CARD_NMT_OUT_PF()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("CARD_NMT_OUT_PF", "26050210022978.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "CARD_NMT_OUT_PF", "CARD_NMT_OUT_PF", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, CARD_NMT_OUT_SO", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_CARD_NMT_OUT_SO()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("CARD_NMT_OUT_SO", "26050210022978.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "CARD_NMT_OUT_SO", "CARD_NMT_OUT_SO", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, NMT_EXPRESSBANK_INCASS_PAY" +
            "M", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_NMT_EXPRESSBANK_INCASS_PAYM()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("NMT_EXPRESSBANK_INCASS_PAYM", "26008230067512.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "NMT_EXPRESSBANK_INCASS_PAYM", "NMT_EXPRESSBANK_INCASS_PAYM", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, NMT_EXTERN_MONEY_WRITEOFF_" +
            "CA", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_NMT_EXTERN_MONEY_WRITEOFF_CA()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("NMT_EXTERN_MONEY_WRITEOFF_CA", "26003210079280.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "NMT_EXTERN_MONEY_WRITEOFF_CA", "NMT_EXTERN_MONEY_WRITEOFF_CA", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, NMT_EXTERN_MONEY_WRITEOFF_" +
            "CARD", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_NMT_EXTERN_MONEY_WRITEOFF_CARD()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("NMT_EXTERN_MONEY_WRITEOFF_CARD", "26050210022978.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "NMT_EXTERN_MONEY_WRITEOFF_CARD", "NMT_EXTERN_MONEY_WRITEOFF_CARD", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, NMT_OUT_CA", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_NMT_OUT_CA()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("NMT_OUT_CA", "260080902977.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "NMT_OUT_CA", "NMT_OUT_CA", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, NMT_OUT_CA_EBANK_PI", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_NMT_OUT_CA_EBANK_PI()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("NMT_OUT_CA_EBANK_PI", "26200210398106.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "NMT_OUT_CA_EBANK_PI", "NMT_OUT_CA_EBANK_PI", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, NMT_OUT_CA_IBANK", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_NMT_OUT_CA_IBANK()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("NMT_OUT_CA_IBANK", "260050103926.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "NMT_OUT_CA_IBANK", "NMT_OUT_CA_IBANK", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, NMT_OUT_CA_IBANK_ST", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_NMT_OUT_CA_IBANK_ST()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("NMT_OUT_CA_IBANK_ST", "26045210380506.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "NMT_OUT_CA_IBANK_ST", "NMT_OUT_CA_IBANK_ST", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, NMT_OUT_CA_SO", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_NMT_OUT_CA_SO()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("NMT_OUT_CA_SO", "260080902977.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "NMT_OUT_CA_SO", "NMT_OUT_CA_SO", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run Natioanl_outgounting_Transfer with example tables, NMT_OUT_CA_ST", new string[] {
                "National_Outgounting_Transfer"}, SourceLine=22)]
        public virtual void RunNatioanl_Outgounting_TransferWithExampleTables_NMT_OUT_CA_ST()
        {
#line 7
this.RunNatioanl_Outgounting_TransferWithExampleTables("NMT_OUT_CA_ST", "26049210173043.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "NMT_OUT_CA_ST", "NMT_OUT_CA_ST", ((string[])(null)));
#line hidden
        }
        
        public virtual void RunNational_Outgounting_Transfer_FreeWithExampleTables(string firstTabPage, string debitAccount, string actualDate, string bankCode, string creditAccount, string reason, string secondTabPage, string currentBpId, string prepareBP, string approveBP, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "National_Outgounting_Transfer_Free"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Run National_Outgounting_Transfer_Free with example tables", @__tags);
#line 42
this.ScenarioSetup(scenarioInfo);
#line 43
testRunner.Given(string.Format("Bank User have been on {0} tab page", firstTabPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 44
testRunner.When(string.Format("Bank User enter debit account {0} for National_MT_Outgoing tab page", debitAccount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 45
testRunner.And(string.Format("Bank User enter actual date {0} for National_MT_Outgoing tab page", actualDate), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 46
testRunner.And("Bank User enter random amount for transfer for National_MT_Outgoing tab page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 47
testRunner.And("Bank User enter random doc number for National_MT_Outgoing tab page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 48
testRunner.And(string.Format("Bank User enter credit bank code {0} for National_MT_Outgoing tab page", bankCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 49
testRunner.And(string.Format("Bank User enter credit account {0} for National_MT_Outgoing tab page", creditAccount), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 50
testRunner.And(string.Format("Bank User enter reason {0} for National_MT_Outgoing tab page", reason), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 51
testRunner.And(string.Format("Bank User finish prepare BP for {0} transfer", prepareBP), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 52
testRunner.Then(string.Format("Bank User have been on {0} tab page", secondTabPage), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 53
testRunner.And(string.Format("Bank User enter current BpId {0}", currentBpId), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 54
testRunner.And(string.Format("Bank User approve BP for {0} transfer", approveBP), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 55
testRunner.And("Bank User check result for National_MT_Outgoing transfer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run National_Outgounting_Transfer_Free with example tables, NMT_OUT_FREE", new string[] {
                "National_Outgounting_Transfer_Free"}, SourceLine=57)]
        public virtual void RunNational_Outgounting_Transfer_FreeWithExampleTables_NMT_OUT_FREE()
        {
#line 42
this.RunNational_Outgounting_Transfer_FreeWithExampleTables("NMT_OUT_FREE", "29006000100523.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "NMT_OUT_FREE", "NMT_OUT_FREE", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run National_Outgounting_Transfer_Free with example tables, NMT_OUT_FREE_1C", new string[] {
                "National_Outgounting_Transfer_Free"}, SourceLine=57)]
        public virtual void RunNational_Outgounting_Transfer_FreeWithExampleTables_NMT_OUT_FREE_1C()
        {
#line 42
this.RunNational_Outgounting_Transfer_FreeWithExampleTables("NMT_OUT_FREE_1C", "36229000106580.980", "getActualDate.sql", "820019", "31115106700002", "*", "BUSINESS_PROCESS_FORM", "getActualBpId.sql", "NMT_OUT_FREE_1C", "NMT_OUT_FREE_1C", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Run CARD_NMT_OUT withou exmaple tables", SourceLine=70)]
        public virtual void RunCARD_NMT_OUTWithouExmapleTables()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Run CARD_NMT_OUT withou exmaple tables", ((string[])(null)));
#line 71
this.ScenarioSetup(scenarioInfo);
#line 72
testRunner.Given("Bank User have been on CARD_NMT_OUT tab page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 73
testRunner.When("Bank User enter debit account 260500194184.980 for National_MT_Outgoing tab page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 74
testRunner.And("Bank User enter actual date getActualDate.sql for National_MT_Outgoing tab page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 75
testRunner.And("Bank User enter random amount for transfer for National_MT_Outgoing tab page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 76
testRunner.And("Bank User enter random doc number for National_MT_Outgoing tab page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 77
testRunner.And("Bank User enter credit bank code 820019 for National_MT_Outgoing tab page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 78
testRunner.And("Bank User enter credit account 31115106700002 for National_MT_Outgoing tab page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 79
testRunner.And("Bank User enter reason * for National_MT_Outgoing tab page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 80
testRunner.And("Bank User finish prepare BP for CARD_NMT_OUT transfer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 81
testRunner.Then("Bank User have been on BUSINESS_PROCESS_FORM tab page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 82
testRunner.And("Bank User enter current BpId getActualBpId.sql", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 83
testRunner.And("Bank User approve BP for CARD_NMT_OUT transfer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 84
testRunner.And("Bank User check result for National_MT_Outgoing transfer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
