using System.Collections.Generic;

namespace CwNetTest.PageObjects
    {
    public class RanorexPathToTestedMenuItems
        { 

        public static Dictionary<string, string> ranorexPath = new Dictionary<string, string>
            {
            ["BUSINESS_PROCESS_FORM"] = "/form[@controlname='MainForm']/?/?/menuitem[@accessiblename='Entry to BackOffice'] , / contextmenu[@controltypename = 'ToolStripDropDownMenu' and @instance = '0'] / menuitem[@accessiblename = 'Money Transfers'] , / contextmenu[@controltypename = 'ToolStripDropDownMenu' and @instance = '1'] / menuitem[@accessiblename = 'Business processes'] , /form[@controlname='MainForm']/?/?/form[@controlname='MultipleBusinessProcessesForm']/?/?/menubar[@controlname='menuStrip2']/menuitem[@accessiblename='Filter']",

            ["NMT_OUT_PF"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text~'^Reimbursement\ not\ transfe']",
            ["CARD_NMT_OUT_EBANK_PI"] = "/form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='National money transfer from card account IBANK'][2]",
            ["NMT_OUT_FREE"] = @"/form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^Free\ Money\ Transfer\ to\ an']",
            ["INB_MT_SALARY_TRANSIT"] = @"/form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text~'^Transfer\ of\ salary\ to\ tra']",
            ["COM_ALERAT_TYPICAL_CONTR_TFA"] = @"/form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text~'^Комісія\ за\ зміну\ типових\ ']",
            ["NMT_OUT_CA_IBANK"] = "/form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='National money transfer from current account IBank'][1]",
            ["CARD_NMT_OUT_IBANK"] = "/form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='National money transfer from card account IBANK'][1]",
            ["NMT_OUT_CA_IBANK_ST"] = "/form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='National money transfer from current account IBank(2604)']",
            ["NMT_OUT_FREE_1C"] = "/form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='Free national MT to another bank 1C']",
            ["CLOSING_FREE_TFA"] = "/form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'],  /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] ,/form[@controlname='MainForm']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='Balance transfer']",
            ["NMT_EXTERN_MONEY_WRITEOFF_CA"] = " /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='External money writeoff fom CA witout arrest']",
            ["CARD_NMT_OUT_PF"] = " /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='Reimbursement pension']",            
            ["CARD_NMT_OUT"] = " /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='National money transfer from card account']",
            ["NMT_OUT_CA_SO"] = " /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='National money transfer from current account(SO)'][2]",
            ["NMT_OUT_CA_EBANK_PI"] = " /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='National money transfer from current account IBank'][2]",
            ["COMM_CREDIT_MANAGEMENT_TFA"] = @"/form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text~'^Комісії\ за\ управління\ кре']",
            ["COMMISSION_FOR_SALARY_TRANSFER"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text~'^Commission\ for\ salary\ tra']",
            ["NMT_EXPRESSBANK_INCASS_PAYM"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text~'^Payment\ for\ incasso']",
            ["INB_MT_GRODI_COMIS"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text~'^Payment\ of\ commission\ for']",
            ["NMT_OUT_CA"] = @"/form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[1]",
            ["CARD_NMT_OUT_EBANK_PI_SO"] = "/form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='National money transfer from card account (SO)'][2]",
            ["CARD_NMT_OUT_SO"] = " /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='National money transfer from card account (SO)'][1]",
            ["NMT_EXTERN_MONEY_WRITEOFF_CARD"] = " /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='External money writeoff fom Card Account witout arrest']",
            ["NMT_OUT_CA_ST"] = " /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^National outgoing transfer'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='National money transfer from current account(2604)']",
            ["INB_MT_SA"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='Transfer to customer SA']",
            ["CASH_TRANSF_WO_ACC"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='National MT Outgoing'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename~'^Cash\ transfer\ without\ ope']",
            ["FREE_TF"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[1]",
            ["INB_MT_CARDACC_CARDACC"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@controlname='MainForm']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@controltypename='TaskItem' and @instance='34']",

            ["INB_MT_CARDACC_SA_PI"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='Transfer from card account to SA PI']",

            ["INB_MT_CA_SA_LE"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'], /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='Transfer from CA to SA LE']",
            ["INB_MT_CARDACC_TDA_PI"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@controlname='MainForm']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='Transfer from card account to TDA PI']",
            ["INB_MT_SA_LE_CA"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='Transfer from SA LE to CA']",
            ["INB_MT_TDA"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='Transfer to customer TDA']",
            ["CL_FUNDS_RETURN"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text~'^Return\ of\ credit\ line\ fun']",
            ["COM_ACCRUE_CERTIF_ZED"] = @" /form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Money Transfers'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='MT within bank'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='2']/menuitem[@accessiblename='Transfers withn bank'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='SystemBPTypeBased_BusinessProcessLaunchForm']/container[@controlname='actionsListPanel1']/?/?/button[@text='ZED comission for CERTIF']",
            ["TERMED_LOAN_REGISTER"] = @"/form[@title='CustomWare.NET']/?/?/menuitem[@accessiblename='Loans'] , /contextmenu[@processname='CustomWareNET.Client']/menuitem[@accessiblename='Loan processes'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='Loans application'] , /form[@title='CustomWare.NET']/?/?/form[@controlname='LoanApplicationSearchForm']/container[@controlname='pnlButtons']/?/?/button[@accessiblename='&New'] , /form[@controlname='LoanTypeForm']/container[@controlname='pnlButtons']/?/?/button[@accessiblename='Ok']",
            ["REGISTER_PRIVATE_INDIVIDUAL"] = "/form[@controlname='MainForm']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Customer Registration'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='Customers registration']",
            ["REGISTER_LEGAL_ENTITY"] = "/form[@controlname='MainForm']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Customer Registration'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='Customers registration']",
            ["CHANGE_CLIENT_CONTACT"] = "/form[@controlname='MainForm']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Customer Registration'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename='User Shell']",
            ["OPEN_INTERNET_BANKING_ACCOUNT"] = @"/form[@controlname='MainForm']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Internet bank management'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename~'^Open\ Internet\ Banking\ Acc']",
            ["MANAGER_INTERNET_BANKING_ACCOUNT"] = @"/form[@controlname='MainForm']/?/?/menuitem[@accessiblename='Entry to Retail module'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='0']/menuitem[@accessiblename='Account Management'] , /contextmenu[@controltypename='ToolStripDropDownMenu' and @instance='1']/menuitem[@accessiblename~'^Manager\ of\ accounts\ openi']"
            };
    }
}
